# Task 6 Exercise5:Use the decision tree generated by Exercise 4 and use the predict function on whether it will rain tomorrow or not. 
# Then plot the predict method outcome (e.g. as a table). 
head(weather)
library(tree)
set.seed(101)
alpha <- 0.7
inTrain <- sample(1:ncol(weather), alpha*ncol(weather))
train.set <- weather[inTrain,]
test.set <- weather[-inTrain,]                  
tree.model3 <- tree(RainTomorrow ~ Sunshine+Cloud9am+Pressure9am, data = train.set)
tree.model4 <- tree(RainTomorrow ~ Sunshine+Cloud9am+Pressure9am, data = test.set)
tree.model3
tree.model4
plot(tree.model3)
text(tree.model3, pretty = 0)
plot(tree.model4)
text(tree.model4, pretty = 0)
predictions3 <-predict(tree.model3,test.set)  # give the probability to each class
head(predictions)
# point the predictions
# Let's translate the probability output to categorical output
maxidx <- function(arr){
  return(which(arr == max(arr)))
}
idx <- apply(predictions3, c(1), maxidx)
prediction4 <- c("Sunshine","pressure9am","Cloud9am")[idx]
# table the predictions
table(prediction4)
summary(tree.model3)
summary(tree.model4)
pruned.tree <- prune.tree(tree.model4, best = 12)
plot(pruned.tree)
text(pruned.tree)
pruned.prediction2 <- predict(pruned.tree, test.set, type = "class")
pruned.prediction2     
table(pruned.prediction2)

